### ISSUE TITLE
error syncing content

### ISSUE THREAD

**Issue by miguelpeixe** [ecodigital/DomeGIS#34]
fatal error syncing content: `bnb2005`

```
TypeError: Cannot read property 'length' of undefined
    at Object.async.eachSeries (/usr/lib/nodejs/async.js:117:17)
    at Request._callback (/vagrant/src/services/content/hooks/index.js:77:15)
```

**Comment by vgeorge** [comment]
ArcGIS Online returns an invalid GeoJSON object for this layer, now the DomeGIS properly handles the error by not crashing and setting layer property `status` to `sync_failed`.
